### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by jjssoftware** [MBvisti/weight-tracker-article#1]
`./main.go:48:35: cannot use storage (type repository.Storage) as type api.UserRepository in argument to api.NewUserService:
        repository.Storage does not implement api.UserRepository (missing UpdateActivityLevel method)`

Seen in GoLand 2020.3.2 w/ go version go1.15.6 linux/amd64

**Comment by MBvisti** [comment]
Thanks for reporting this issue. This was originally ment to be in the article, but decided against it. I will fix this asap. If you want to just get building, remove the method from the userRepository in user.go.

**Comment by jjssoftware** [comment]
No problem, it isn't a problem for me but it could be a problem for Go beginners, this being the audience your article intends to target. Being able to build, run and line step debug code can be a fundamental foundation piece in learning.

As an aside what follows is that I hope is a little piece of constructive criticism about your code for this article: 

I think that the code here goes too far beyond the subject of the article "How to structure Golang applications".

The reason I say this is that the code introduces too many external dependencies and concepts (i.e. database) that are largely irrelevant to correct code structure. IMO the general approach of the article and code should be to structure code in the suggested correct way at the various tiers (API / Service / Repository) without introducing the complexity of specifics at the tiers. In other words structure the code as it needs to be in the tiers and comment the intention at the various levels in the tiers and stub the behaviour of the request / response data through the tiers. If the article code looked like this it would be 1) more simple to understand for beginners 2) easier for beginners to get running (no need to install a db etc) 3) more closely meet the intent of "How to structure Golang applications".

Please don't construe this feedback as an attack because that is not the intent, I mean for it to be constructive criticism and I applaud you for general intent of the article which is to educate.

One final note, your [README.md](https://github.com/MBvisti/weight-tracker-article/blob/master/README.md) contains a broken link back to the article. 

All the best, Joe

**Comment by MBvisti** [comment]
Nice catch, this is my first article and should probably have made a "publish-check-list".

Not at all, I'm always open to constructive criticisms. I get where you are coming from and I do see some merit to that approach. However, as I mention in the article, this is what I would have needed when I first started out writing Golang apps. I wouldn't have learned well from the approach you suggest, as I need some more hand-on and practical. Please don't take it as I'm not welcoming your feedback, this is written for me 2 years back in time. The goal was to give beginners a complete base to start from without having to figure things like external dependencies out. That could have been clear in the introduction, I'll admit.

Once again, thanks for your feedback, really appreciated :)!

**Comment by MBvisti** [comment]
This is fixed so closing now.
